# Generated by Django 3.2.9 on 2022-05-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=3)),
                ('year', models.PositiveIntegerField(default=2015)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('qrcode', models.ImageField(upload_to='qr/')),
            ],
        ),
    ]
